name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Dovyski/setup-opencv-action@v1
      with:
        opencv-version: '4.5.4'
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
